In [7]:
import numpy as np

a = np.random.randn(5) #dont use this way
print(a)
print(a.shape)


[-1.52109095 -0.59157376 -1.86006227 -0.18588539  0.5693023 ]
(5,)


In [9]:
print(a*a.T)

[2.31371769 0.34995952 3.45983166 0.03455338 0.32410511]


In [3]:
a = np.random.randn(5,1) # This this wa#
print(a)

[[-0.75460831]
 [-0.57143936]
 [ 0.71974502]
 [ 0.48342555]
 [ 0.4103421 ]]


In [4]:
print(a.T)

[[-0.75460831 -0.57143936  0.71974502  0.48342555  0.4103421 ]]


In [5]:
print(a*a.T)

[[ 0.5694337   0.43121289 -0.54312557 -0.36479693 -0.30964755]
 [ 0.43121289  0.32654294 -0.41129063 -0.27624839 -0.23448562]
 [-0.54312557 -0.41129063  0.5180329   0.34794313  0.29534168]
 [-0.36479693 -0.27624839  0.34794313  0.23370026  0.19836985]
 [-0.30964755 -0.23448562  0.29534168  0.19836985  0.16838064]]
