In [2]:
import numpy as np

a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tik = time.time()
c = np.dot(a,b)
tok = time.time()
print("Vectorization product time: " + str(1000*(tok-tik)) + "ms" )
print(c)

c=0
tik = time.time()
for i in range(1000000):
    c+= a[i] * b[i] 
tok = time.time()
    
print("Non-Vectorization product time: " + str(1000*(tok-tik)) + "ms" )
print(c)


Vectorization product time: 0.5717277526855469ms
250203.5994719294
Non-Vectorization product time: 713.9770984649658ms
250203.59947193545


In [5]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[-1.12971283  0.11814624  0.56305904]
 [ 0.53136634  0.07649368 -0.48930336]
 [ 0.3684947  -0.43926654 -1.73254056]]
[[-2.02905666]
 [-0.08362677]
 [ 0.76696491]]
[[ 2.29225135 -0.23972542 -1.14247869]
 [-0.04443645 -0.00639692  0.04091886]
 [ 0.2826225  -0.33690202 -1.32879781]]
